# Generated by Django 3.1.7 on 2021-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0007_auto_20210320_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='netflix.Category'),
        ),
    ]
